# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Interface(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(500, 400)
        Window.setStyleSheet("QPushButton {\n"
                             "    border-radius: 15px;\n"
                             "    background-color: rgb(184, 186, 186);\n"
                             "    \n"
                             "}\n"
                             "\n"
                             "QPushButton::hover {\n"
                             "    background-color: rgb(215, 218, 218);\n"
                             "}\n"
                             "\n"
                             "QLineEdit {\n"
                             "    border-radius: 15px;\n"
                             "    padding-left: 10px;\n"
                             "}\n"
                             "\n"
                             "QTextBrowser {\n"
                             "    border-radius: 15px;\n"
                             "    background-color: rgb(217, 220, 220);\n"
                             "}")
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 500, 381))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Chat = QtWidgets.QWidget()
        self.Chat.setObjectName("Chat")
        self.Message = QtWidgets.QLineEdit(self.Chat)
        self.Message.setGeometry(QtCore.QRect(15, 170, 445, 41))
        self.Message.setObjectName("Message")
        self.Send = QtWidgets.QPushButton(self.Chat)
        self.Send.setEnabled(True)
        self.Send.setGeometry(QtCore.QRect(2, 231, 471, 51))
        self.Send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Send.setCheckable(True)
        self.Send.setObjectName("Send")
        self.Connect = QtWidgets.QPushButton(self.Chat)
        self.Connect.setGeometry(QtCore.QRect(2, 290, 471, 51))
        self.Connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Connect.setObjectName("Connect")
        self.Information = QtWidgets.QTextBrowser(self.Chat)
        self.Information.setGeometry(QtCore.QRect(15, 20, 445, 121))
        self.Information.setObjectName("Information")
        self.tabWidget.addTab(self.Chat, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.lineEdit = QtWidgets.QLineEdit(self.Settings)
        self.lineEdit.setGeometry(QtCore.QRect(5, 70, 460, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Settings)
        self.lineEdit_2.setGeometry(QtCore.QRect(5, 140, 460, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.Settings)
        self.pushButton.setGeometry(QtCore.QRect(5, 230, 460, 51))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.Settings, "")
        Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "AkChat"))
        self.Message.setPlaceholderText(_translate("Window", "Введите свое сообщение сюда"))
        self.Send.setText(_translate("Window", "Отправить"))
        self.Connect.setText(_translate("Window", "Подключится"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Chat), _translate("Window", "Чат"))
        self.lineEdit.setPlaceholderText(_translate("Window", "Адресс сервера"))
        self.lineEdit_2.setPlaceholderText(_translate("Window", "Порт сервера"))
        self.pushButton.setText(_translate("Window", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("Window", "Настройки"))
